export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";

export const UPDATE_STATUS_REQUEST_SUCCESS = "UPDATE_STATUS_REQUEST_SUCCESS";

export const UPDATE_STATUS_REQUEST_FAILURE = "UPDATE_STATUS_REQUEST_FAILURE";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";

export const GET_STATUS_REQUEST_SUCCESS = "GET_STATUS_REQUEST_SUCCESS";

export const GET_STATUS_REQUEST_FAILURE = "GET_STATUS_REQUEST_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";

export const GET_PROFILE_REQUEST_SUCCESS = "GET_PROFILE_REQUEST_SUCCESS";

export const GET_PROFILE_REQUEST_FAILURE = "GET_PROFILE_REQUEST_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";

export const UPDATE_PROFILE_REQUEST_SUCCESS = "UPDATE_PROFILE_REQUEST_SUCCESS";

export const UPDATE_PROFILE_REQUEST_FAILURE = "UPDATE_PROFILE_REQUEST_FAILURE";
