export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST";

export const GET_CONVERSATION_REQUEST_SUCCESS =
  "GET_CONVERSATION_REQUEST_SUCCESS";

export const GET_CONVERSATION_REQUEST_FAILURE =
  "GET_CONVERSATION_REQUEST_FAILURE";
