export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST";

export const GET_CONVERSATION_REQUEST_SUCCESS =
  "GET_CONVERSATION_REQUEST_SUCCESS";

export const GET_CONVERSATION_REQUEST_FAILURE =
  "GET_CONVERSATION_REQUEST_FAILURE";

export const SEARCH_CONVERSATION_REQUEST = "SEARCH_CONVERSATION_REQUEST";

export const SEARCH_CONVERSATION_REQUEST_SUCCESS =
  "SEARCH_CONVERSATION_REQUEST_SUCCESS";

export const SEARCH_CONVERSATION_REQUEST_FAILURE =
  "SEARCH_CONVERSATION_REQUEST_FAILURE";
